kind: Service
apiVersion: v1
metadata:
  name: datapower-quickstart
spec:
  ports:
    - name: webui
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/instance: datapower-quickstart
  type: ClusterIP
  sessionAffinity: None

