FROM ibmcom/datapower:latest
ENV  DATAPOWER_ACCEPT_LICENSE=true \
     DATAPOWER_INTERACTIVE=true \
     DATAPOWER_WORKER_THREADS=4

COPY datapower-services/dp-demo/drouter/config /opt/ibm/datapower/drouter/config
COPY datapower-services/dp-demo/drouter/local /opt/ibm/datapower/drouter/local
COPY datapower-services/dp-demo/drouter/secure/usrcerts /opt/ibm/datapower/root/secure/usrcerts

USER root
RUN chown -R drouter:root /opt/ibm/datapower/drouter/config \
                          /opt/ibm/datapower/drouter/local \
                          /opt/ibm/datapower/root/secure/usrcerts
RUN  set-user drouter
USER drouter

EXPOSE 9090 6443