bases:
- https://github.com/APILabs/Datapower-tutorials/Openshift/Lab3/deploy?ref=main
- namespace.yaml
- ibm-entitlement-key.yaml
patchesJson6902:
  - target:
      version: v1
      group: route.openshift.io
      kind: Route
      name: quickstart-webui
    path: route.yaml