apiVersion: datapower.ibm.com/v1beta2
kind: DataPowerService
metadata:
  name: quickstart
spec:
  license:
    accept: true
    use: nonproduction
  imagePullSecrets:
    - ibm-entitlement-key
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 4
      memory: 4Gi
  users:
    - name: admin
      accessLevel: privileged
      passwordSecret: admin-secret
  domains:
    - dpApp:
        config:
          - web-mgmt
      name: default
    - name: IDP
      certs:
      - certType: "usrcerts"
        secret: "idp-crypto-secret"
      dpApp:
        config:
          - idp-domain-config"
        local:
          - idp-domain-local"
  version: 10.0-eus
  podManagementPolicy: OrderedReady
  replicas: 1
  
