kind: Service
apiVersion: v1
metadata:
  name: demo-quickstart
spec:
  ports:
    - name: demosvc
      protocol: TCP
      port: 6443
      targetPort: 6443
  selector:
    app.kubernetes.io/name: datapower
  type: ClusterIP
  sessionAffinity: None

