kind: Secret
apiVersion: v1
metadata:
  name: ibm-entitlement-key
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJjcC5pY3IuaW8iOnsidXNlcm5hbWUiOiJjcCIsInBhc3N3b3JkIjoiZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcGMzTWlPaUpKUWswZ1RXRnlhMlYwY0d4aFkyVWlMQ0pwWVhRaU9qRTJNVEl3T1RZek16Y3NJbXAwYVNJNkltVXdaall3TkRRMk1EVTFOelJoTmpKaVpHVTFNelk0WlRFeU5tTXlPRFkxSW4wLjRhQnpmM3dRR1JfQWN6QVVsVVNoX0FGRUhNNkZDVHZSQnVLbi1YNTkwcnciLCJhdXRoIjoiWTNBNlpYbEthR0pIWTJsUGFVcEpWWHBKTVU1cFNqa3VaWGxLY0dNelRXbFBhVXBLVVdzd1oxUlhSbmxoTWxZd1kwZDRhRmt5VldsTVEwcHdXVmhSYVU5cVJUSk5WRWwzVDFSWmVrMTZZM05KYlhBd1lWTkpOa2x0VlhkYWFsbDNUa1JSTWsxRVZURk9lbEpvVG1wS2FWcEhWVEZOZWxrMFdsUkZlVTV0VFhsUFJGa3hTVzR3TGpSaFFucG1NM2RSUjFKZlFXTjZRVlZzVlZOb1gwRkdSVWhOTmtaRFZIWlNRblZMYmkxWU5Ua3djbmM9In19fQ==
type: kubernetes.io/dockerconfigjson